name: test-py6s
on: [push]
jobs:
  test-py6s:
    name: Test Py6S
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: 3.7
          channels: conda-forge
          activate-environment: py6s-test
      - name: Install conda dependencies
        shell: bash -l {0}
        run: |
          conda install sixs pysolar numpy scipy pandas matplotlib pytest pytest-cov
      - name: Install pip dependencies
        shell: bash -l {0}
        run: |
          pip install python-coveralls
          pip install coverage==4.4
      - name: Install Py6S
        shell: bash -l {0}
        run: python setup.py install
      - name: Run tests
        shell: bash -l {0}
        run: python -m pytest -v --junitxml=result.xml --cov Py6S --cov-report term-missing